CREATE TABLE IF NOT EXISTS szereplok (
    `szinesz` VARCHAR(22) CHARACTER SET utf8,
    `karaker` VARCHAR(18) CHARACTER SET utf8,
    `epizodok` INT,
    `idosavid` INT
);
INSERT INTO szereplok VALUES
    ('Rami Malek','Elliot Alderson',46,3),
    ('Christian Slater','Mr. Robot',45,3),
    ('Carly Chaikin','Darlene',43,3),
    ('Martin Wallström','Tyrell Wellick',38,3),
    ('Portia Doubleday','Angela Moss',36,3),
    ('Michael Cristofer','Phillip Price',32,3),
    ('Grace Gummer','Dominique DiPierro',31,5),
    ('BD Wong','Whiterose',22,3),
    ('Stephanie Corneliussen','Joanna Wellick',21,2),
    ('Vaishnavi Sharma','Elliot''s Mother',17,3),
    ('Gloria Reuben','Krista Gordon',16,3),
    ('Sunita Mani','Trenton',16,3),
    ('Azhar Khan','Mobley',15,3),
    ('Joey Bada$$','Leon',13,5),
    ('Omar Metwally','Agent Santiago',13,4),
    ('Michael Drayer','Cisco',12,2),
    ('Michel Gill','Gideon Goddard',11,2),
    ('Jeremy Holm','Mr. Sutherland',11,2),
    ('Annika Pergament','Annika Pergament',7,3),
    ('Bobby Cannavale','Irvin',9,7),
    ('Ben Rappaport','Ollie Parker',9,3),
    ('Grant Chang','Grant',9,4),
    ('Elliot Villar','Fernando Vera',8,3),
    ('Ron Cephas Jones','Romero',8,3),
    ('Frankie Shaw','Shayla Nico',8,3),
    ('Brian Stokes Mitchell','Scott Knowles',8,1),
    ('Erik Jensen','Frank Cody',8,4),
    ('Sakina Jaffrey','Antara Nayar',7,2),
    ('Aaron Takahashi','Lloyd Chung',7,3),
    ('Craig Robinson','Ray',7,5),
    ('Aidan Liebman','Young Elliot',7,3),
    ('Evan Whitten','Young Elliot',6,8);
